"""Experiment blueprint inference and dependency-free project generation."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import json
import re
import secrets
import textwrap
from typing import Any, Mapping

from .models import Claim, ExperimentBlueprint, Paper, utc_now


_METRIC_NAMES = ("accuracy", "precision", "recall", "f1", "f1-score", "bleu", "rouge", "auc", "loss", "latency", "exact match", "pass rate", "score")


def _first_sentence(value: str, default: str = "Not specified") -> str:
    value = re.sub(r"\s+", " ", value or "").strip()
    if not value:
        return default
    return re.split(r"(?<=[.!?。！？])\s+", value)[0][:500]


def _find_section(paper: Paper | None, names: set[str]) -> str:
    if not paper:
        return ""
    # Prefer the semantically strongest section when callers provide a set
    # containing several fallbacks (e.g. Results → Abstract → Ablation).
    priority = ["results", "method", "dataset", "experiment", "abstract", "ablation", "introduction"]
    ordered = [name for name in priority if name in names] + [name for name in names if name not in priority]
    for wanted in ordered:
        for section in paper.sections:
            if section.title.lower() == wanted and section.content.strip():
                return section.content
    return ""


@dataclass
class BlueprintBuilder:
    """Turn a claim into an explicit, editable experiment plan."""

    def build(self, claim: Claim, paper: Paper | None = None, **overrides: Any) -> ExperimentBlueprint:
        text = claim.claim_text.strip()
        lower = text.lower()
        dataset_text = _find_section(paper, {"dataset", "experiment"})
        method_text = _find_section(paper, {"method", "experiment"})
        result_text = _find_section(paper, {"results", "abstract", "ablation"})
        metrics: list[str] = []
        metric_text = (lower + " " + result_text.lower()).replace("-", " ")
        for metric in _METRIC_NAMES:
            if re.search(rf"\b{re.escape(metric.replace('-', ' '))}\b", metric_text):
                metrics.append(metric)
        if not metrics:
            metrics = ["accuracy"]
        variables: list[str] = []
        for token in ("retrieval", "memory", "context length", "number of tools", "prompt", "learning rate", "model size", "seed"):
            if token in lower or token in method_text.lower():
                variables.append(token)
        if not variables:
            variables = ["method configuration"]
        dependent = metrics[:]
        if "latency" in lower and "latency" not in dependent:
            dependent.append("latency")
        dataset = _first_sentence(dataset_text)
        model = _first_sentence(method_text)
        if "rag" in lower or "retriev" in lower:
            baseline = "No-retrieval baseline"
        elif "memory" in lower:
            baseline = "No-memory baseline"
        else:
            baseline = "Simple or published baseline (verify implementation)"
        expected = f"The local run should reproduce the direction of the claim: {text}"
        blueprint = ExperimentBlueprint(
            paper_id=claim.paper_id or (paper.paper_id if paper else ""),
            claim_id=claim.claim_id,
            research_question=f"Can we reproduce the claim: {text}",
            hypothesis=f"{text} holds under the documented dataset, model, and evaluation procedure.",
            independent_variables=variables,
            dependent_variables=dependent,
            controls=["fixed seed", "same evaluation split", "record software environment"],
            dataset=dataset,
            model=model,
            baseline=baseline,
            metrics=metrics,
            expected_result=expected,
            implementation_plan=[
                "Verify the paper's dataset, split, preprocessing, and license.",
                "Implement the stated method and baseline with unresolved pieces marked TODO.",
                "Run a fixed-seed smoke test, then evaluate every reported metric.",
                "Record environment, stdout/stderr, and compare local values with the paper.",
            ],
            paper_reported_result=self._extract_results(result_text, metrics),
            notes="Generated by deterministic BlueprintBuilder. Verify every field against the paper before spending compute.",
        )
        for key, value in overrides.items():
            if hasattr(blueprint, key):
                setattr(blueprint, key, value)
        return blueprint

    def validate(self, blueprint: ExperimentBlueprint) -> list[str]:
        errors: list[str] = []
        required = {
            "research_question": blueprint.research_question,
            "hypothesis": blueprint.hypothesis,
            "dataset": blueprint.dataset,
            "model": blueprint.model,
            "baseline": blueprint.baseline,
        }
        for name, value in required.items():
            if not str(value).strip() or str(value).strip().lower() == "not specified":
                errors.append(f"Missing or unverified field: {name}")
        if not blueprint.metrics:
            errors.append("At least one metric is required")
        if not blueprint.independent_variables:
            errors.append("At least one independent variable is required")
        return errors

    @staticmethod
    def _extract_results(text: str, metrics: list[str]) -> dict[str, Any]:
        result: dict[str, Any] = {}
        source = text or ""
        # First handle prose such as ``accuracy improves to 81.4%``.  Avoid
        # capturing a value from a later sentence by keeping the window tight.
        for metric in metrics:
            match = re.search(
                rf"\b{re.escape(metric)}\b[^.\n|]{{0,80}}?(\d+(?:\.\d+)?)\s*%?",
                source,
                re.I,
            )
            if match:
                result[metric] = float(match.group(1))

        # Markdown/HTML-to-text tables are common in papers.  Parse the header
        # and use the last data row (usually the proposed method) without
        # pretending that this is a full table extraction system.
        lines = [line.strip() for line in source.splitlines() if "|" in line]
        if len(lines) >= 3:
            def cells(line: str) -> list[str]:
                return [part.strip() for part in line.strip().strip("|").split("|")]
            header = cells(lines[0])
            data_lines = [line for line in lines[1:] if not re.fullmatch(r"[|\s:-]+", line)]
            if data_lines:
                row = cells(data_lines[-1])
                for metric in metrics:
                    idx = next((i for i, cell in enumerate(header) if cell.casefold().replace("-", " ") == metric.casefold().replace("-", " ")), None)
                    if idx is not None and idx < len(row):
                        number = re.search(r"[-+]?\d+(?:\.\d+)?", row[idx])
                        if number:
                            # The final row is normally the proposed method;
                            # prefer it over a prose/header match such as the
                            # no-memory baseline.
                            result[metric] = float(number.group(0))
        return result


class CodeSkeletonGenerator:
    """Generate a new, clearly marked experiment project.

    No model implementation is invented.  The generated ``run.py`` is a
    deterministic smoke experiment only and reports TODOs in its output.
    """

    directories = ("experiments", "configs", "datasets", "models", "evaluators", "results", "reports", "tests")

    def generate(self, blueprint: ExperimentBlueprint, target_dir: str | Path, overwrite: bool = False) -> Path:
        root = Path(target_dir).expanduser().resolve()
        if root.exists() and any(root.iterdir()) and not overwrite:
            raise FileExistsError(f"Target directory is not empty: {root}")
        root.mkdir(parents=True, exist_ok=True)
        for directory in self.directories:
            (root / directory).mkdir(parents=True, exist_ok=True)
        config = {
            "schema_version": "1.0",
            "blueprint_id": blueprint.blueprint_id,
            "paper_id": blueprint.paper_id,
            "claim_id": blueprint.claim_id,
            "seed": 42,
            "mode": "mock",
            "metrics": blueprint.metrics,
            "implementation_plan": blueprint.implementation_plan,
            "dataset": blueprint.dataset,
            "model": blueprint.model,
            "baseline": blueprint.baseline,
            "todo": ["Implement the paper's model and data pipeline; this skeleton intentionally does not pretend they exist."],
        }
        # JSON is valid YAML 1.2 and lets the generated standard-library
        # ``run.py`` load the file without PyYAML.  Keep the requested
        # ``config.yaml`` filename while avoiding a misleading YAML parser
        # dependency in the offline skeleton.
        config_text = json.dumps(config, ensure_ascii=False, indent=2) + "\n"
        self._write(root / "config.yaml", config_text)
        # Keep the compatibility root config and expose the requested
        # ``configs/`` layout for projects that will grow multiple variants.
        self._write(root / "configs" / "config.yaml", config_text)
        manifest = {
            "project": "Paper2Lab experiment skeleton",
            "created_at": utc_now(),
            "blueprint": blueprint.to_dict(),
            "generated_by": "CodeSkeletonGenerator/offline-v1",
            "implementation_status": "skeleton",
        }
        self._write(root / "manifest.json", json.dumps(manifest, ensure_ascii=False, indent=2) + "\n")
        self._write(root / "run.py", self._run_script())
        self._write(root / "evaluator.py", self._evaluator_script())
        self._write(root / "README.md", self._readme(blueprint))
        self._write(root / "tests" / "test_smoke.py", "from pathlib import Path\n\ndef test_skeleton_files_exist():\n    root = Path(__file__).parents[1]\n    assert (root / 'config.yaml').exists()\n    assert (root / 'run.py').exists()\n")
        return root

    @staticmethod
    def _write(path: Path, content: str) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    @staticmethod
    def _run_script() -> str:
        return textwrap.dedent(
            '''\
            """Deterministic Paper2Lab smoke run; replace TODOs with real code."""
            from __future__ import annotations
            import argparse, json, random, time
            from pathlib import Path

            ROOT = Path(__file__).resolve().parent
            parser = argparse.ArgumentParser()
            parser.add_argument("--config", default=str(ROOT / "config.yaml"))
            parser.add_argument("--output", default=str(ROOT / "results" / "results.json"))
            parser.add_argument("--seed", type=int, default=None)
            args = parser.parse_args()
            config = json.loads(Path(args.config).read_text(encoding="utf-8"))
            seed = int(args.seed if args.seed is not None else config.get("seed", 42))
            rng = random.Random(seed)
            started = time.time()
            # TODO: implement the paper-specific dataset, model, and training procedure.
            metric_names = list(config.get("metrics", ["accuracy"]))
            metrics = {str(metric): round(0.5 + rng.random() * 0.1, 4) for metric in metric_names}
            results = {
                "status": "mock_skeleton",
                "mode": "mock",
                "metrics": metrics,
                "todo": config.get("todo", []),
                "seed": seed,
                "runtime_seconds": round(time.time() - started, 6),
            }
            out = Path(args.output)
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(json.dumps(results, indent=2), encoding="utf-8")
            print(json.dumps(results, indent=2))
            '''
        )

    @staticmethod
    def _evaluator_script() -> str:
        return '''"""Compare local result JSON with paper-reported values."""\nfrom __future__ import annotations\n\ndef compare(paper: dict, local: dict) -> dict:\n    paper_metrics = paper.get("metrics", paper) if isinstance(paper, dict) else {}\n    local_metrics = local.get("metrics", local) if isinstance(local, dict) else {}\n    output = {}\n    for metric, expected in paper_metrics.items():\n        actual = local_metrics.get(metric)\n        if isinstance(expected, (int, float)) and isinstance(actual, (int, float)):\n            delta = actual - expected\n            output[metric] = {"paper": expected, "local": actual, "difference": delta, "status": "match" if abs(delta) < 1e-3 else "different"}\n        else:\n            output[metric] = {"paper": expected, "local": actual, "status": "missing" if actual is None else "uncomparable"}\n    return output\n'''

    @staticmethod
    def _readme(blueprint: ExperimentBlueprint) -> str:
        metrics = ", ".join(blueprint.metrics) or "(verify)"
        return f'''# Paper2Lab Experiment Skeleton\n\nThis directory was generated from blueprint `{blueprint.blueprint_id}`.\n\n## Research question\n{blueprint.research_question}\n\n## Hypothesis\n{blueprint.hypothesis}\n\n## Planned metrics\n{metrics}\n\n## Important\n`run.py` executes a deterministic **mock skeleton** only. It does not claim to implement the paper's model, dataset, or training procedure. Replace each `TODO` after checking the source paper and legal data availability.\n\nRun locally:\n\n```text\npython run.py\n```\n\nResults are written to `results/results.json`; environment and seed must be recorded before a real reproduction.\n'''


def build_blueprint(claim: Claim, paper: Paper | None = None, **overrides: Any) -> ExperimentBlueprint:
    return BlueprintBuilder().build(claim, paper, **overrides)
