"""Provider interfaces with deterministic, offline development providers."""

from __future__ import annotations

from dataclasses import dataclass, field
from hashlib import sha256
import json
import re
from typing import Any, Iterable, Mapping, Protocol


@dataclass
class ProviderResponse:
    text: str
    provider: str = "mock"
    model: str = "mock-v1"
    usage: dict[str, int] = field(default_factory=dict)
    network_used: bool = False
    metadata: dict[str, Any] = field(default_factory=dict)

    def __str__(self) -> str:
        return self.text


class LLMProvider(Protocol):
    """Stable future-facing interface; implementations must be local-safe."""

    name: str

    def generate(self, prompt: str, **kwargs: Any) -> ProviderResponse: ...

    def stream(self, prompt: str, **kwargs: Any) -> Iterable[str]: ...

    def embed(self, text: str, dimensions: int = 16, **kwargs: Any) -> list[float]: ...

    def count_tokens(self, text: str) -> int: ...


class MockLLMProvider:
    """A deterministic provider that never performs network access.

    ``canned_responses`` may map an exact prompt or a substring to a response,
    which makes tests and demos repeatable without an API key.
    """

    name = "mock"
    # Exposed as a provider-level capability flag as well as on each response,
    # so the UI and audit code can state the offline guarantee without making
    # a request first.
    network_used = False

    def __init__(self, seed: int = 0, canned_responses: Mapping[str, str] | None = None, model: str = "mock-v1") -> None:
        self.seed = seed
        self.model = model
        self.canned_responses = dict(canned_responses or {})

    def generate(self, prompt: str, **kwargs: Any) -> ProviderResponse:
        response = self._lookup(prompt)
        if response is None:
            digest = sha256(f"{self.seed}:{prompt}".encode("utf-8")).hexdigest()[:10]
            # Keep the answer visibly synthetic so it cannot be mistaken for a
            # claim that came from a real model.
            response = f"[MOCK RESPONSE {digest}] Offline analysis placeholder for: {self._one_line(prompt)}"
        tokens_in = self.count_tokens(prompt)
        tokens_out = self.count_tokens(response)
        return ProviderResponse(
            text=response,
            provider=self.name,
            model=self.model,
            usage={"prompt_tokens": tokens_in, "completion_tokens": tokens_out, "total_tokens": tokens_in + tokens_out},
            network_used=False,
            metadata={"seed": self.seed},
        )

    def stream(self, prompt: str, **kwargs: Any) -> Iterable[str]:
        text = self.generate(prompt, **kwargs).text
        # A predictable small-chunk stream mimics UI streaming without a
        # background thread or network call.
        for match in re.finditer(r"\S+\s*", text):
            yield match.group(0)

    def embed(self, text: str, dimensions: int = 16, **kwargs: Any) -> list[float]:
        dimensions = max(1, int(dimensions))
        digest = sha256(f"{self.seed}:{text}".encode("utf-8")).digest()
        values: list[float] = []
        for i in range(dimensions):
            byte = digest[i % len(digest)]
            values.append(round((byte / 127.5) - 1.0, 6))
        return values

    def count_tokens(self, text: str) -> int:
        # Transparent approximation; no tokenizer dependency is needed for the
        # local app.  CJK characters count individually, words as one token.
        pieces = re.findall(r"[\u4e00-\u9fff]|[A-Za-z0-9_]+|[^\s]", text or "")
        return len(pieces)

    def _lookup(self, prompt: str) -> str | None:
        if prompt in self.canned_responses:
            return self.canned_responses[prompt]
        for key, value in self.canned_responses.items():
            if key and key.lower() in prompt.lower():
                return value
        return None

    @staticmethod
    def _one_line(prompt: str, limit: int = 140) -> str:
        value = re.sub(r"\s+", " ", prompt).strip()
        return value if len(value) <= limit else value[: limit - 1] + "…"


class RuleBasedProvider(MockLLMProvider):
    """Offline provider with a few structured prompt conveniences."""

    name = "rule-based"

    def generate(self, prompt: str, **kwargs: Any) -> ProviderResponse:
        if "json" in prompt.lower() or "structured" in prompt.lower():
            payload = {"status": "offline", "note": "Generated by RuleBasedProvider; verify against source paper.", "prompt": self._one_line(prompt)}
            return ProviderResponse(json.dumps(payload, ensure_ascii=False), self.name, self.model, network_used=False)
        return super().generate(prompt, **kwargs)


class ProviderRegistry:
    def __init__(self) -> None:
        self._providers: dict[str, LLMProvider] = {}

    def register(self, name: str, provider: LLMProvider) -> None:
        self._providers[name] = provider

    def get(self, name: str = "mock") -> LLMProvider:
        if name not in self._providers:
            raise KeyError(f"Unknown provider: {name}")
        return self._providers[name]

    def names(self) -> list[str]:
        return sorted(self._providers)


FUTURE_PROVIDER_NAMES = ("openai", "anthropic", "google", "local-ollama", "custom-http")


class DeferredProvider:
    """Explicit placeholder for a future provider; never performs network I/O."""

    def __init__(self, name: str) -> None:
        self.name = name
        self.network_used = False

    def generate(self, prompt: str, **kwargs: Any) -> ProviderResponse:
        raise NotImplementedError(f"Provider '{self.name}' is reserved but not implemented in the offline build.")

    def stream(self, prompt: str, **kwargs: Any) -> Iterable[str]:
        raise NotImplementedError(f"Provider '{self.name}' is reserved but not implemented in the offline build.")

    def embed(self, text: str, dimensions: int = 16, **kwargs: Any) -> list[float]:
        raise NotImplementedError(f"Provider '{self.name}' is reserved but not implemented in the offline build.")

    def count_tokens(self, text: str) -> int:
        return MockLLMProvider().count_tokens(text)


def default_registry(seed: int = 0) -> ProviderRegistry:
    registry = ProviderRegistry()
    registry.register("mock", MockLLMProvider(seed=seed))
    registry.register("rule-based", RuleBasedProvider(seed=seed))
    # Keep future integrations visible in settings without making them look
    # implemented: selecting one returns an explicit NotImplementedError and
    # never falls through to network I/O.
    for name in FUTURE_PROVIDER_NAMES:
        registry.register(name, DeferredProvider(name))
    return registry


__all__ = [
    "ProviderResponse", "LLMProvider", "MockLLMProvider", "RuleBasedProvider",
    "ProviderRegistry", "DeferredProvider", "FUTURE_PROVIDER_NAMES", "default_registry",
]
